version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/examples/mini-app"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "mini-app"
    commit-message:
      prefix: "chore"
      include: "scope"