name: "Chromatic"

on: pull_request

jobs:
  chromatic:
    name: Run Chromatic
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.title, '[draft]')"
    defaults:
      run:
        working-directory: ./examples/mini-app

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: rm ../../package.json ../../pnpm-lock.yaml

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Enable Corepack
        run: corepack enable

      - name: Install pnpm
        run: corepack use pnpm@latest-10

      - name: Install dependencies
        run: pnpm install --ignore-workspace

      - name: Run Chromatic
        uses: chromaui/action@latest
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          workingDir: examples/mini-app
          exitZeroOnChanges: false
          skip: "dependabot/**"
