name: Claude Assistant

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  issues:
    types: [opened, assigned, labeled]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  claude-response:
    runs-on: ubuntu-latest
    steps:
      - uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          # Optional configurations below:
          # trigger_phrase: "@claude"  # default is @claude
          # max_turns: "10"  # limit conversation turns
          # timeout_minutes: "30"  # default timeout
          # allowed_tools: |  # additional tools Claude can use
          #   Bash(npm install)
          #   Bash(npm test)
          # custom_instructions: |  # additional instructions for Claude
          #   Always write tests for new functions
          #   Follow the project's coding standards